version: '3.4'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  
  kafka:
    image: wurstmeister/kafka:0.10.2.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_CREATE_TOPICS: "sendtopic:1:1,rettopic:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  
  sql.data:
    image: microsoft/mssql-server-linux:2017-latest
 
  convenio.api:
    image: ${DOCKER_REGISTRY}convenioapi
    build:
      context: .
      dockerfile: Convenio.API/Dockerfile
    depends_on:
      - sql.data

  pago.api:
    image: ${DOCKER_REGISTRY}pagoapi
    build:
      context: .
      dockerfile: Pago.API/Dockerfile

  dispatcherkafka:
    image: ${DOCKER_REGISTRY}dispatcherkafka
    build:
      context: .
      dockerfile: DispatcherKafka/Dockerfile
    depends_on:
      - convenio.api
      - pago.api

  ocelotapigw:
    image: ${DOCKER_REGISTRY}ocelotapigw
    build:
      context: .
      dockerfile: OcelotApiGw/Dockerfile
    depends_on: 
      - convenio.api
      - pago.api      