version: '3.4'

services:
  sql.data:
    image: microsoft/mssql-server-linux:2017-latest
 
  convenio.api:
    image: ${DOCKER_REGISTRY}convenioapi
    build:
      context: .
      dockerfile: Convenio.API/Dockerfile
    depends_on:
      - sql.data

  pago.api:
    image: ${DOCKER_REGISTRY}pagoapi
    build:
      context: .
      dockerfile: Pago.API/Dockerfile

  dispatcherkafka:
    image: ${DOCKER_REGISTRY}dispatcherkafka
    build:
      context: .
      dockerfile: DispatcherKafka/Dockerfile
    depends_on:
      - convenio.api
      - pago.api

  ocelotapigw:
    image: ${DOCKER_REGISTRY}ocelotapigw
    build:
      context: .
      dockerfile: OcelotApiGw/Dockerfile
    depends_on: 
      - convenio.api
      - pago.api      

