version: '3.4'

services:
  ocelotapigw:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  convenio.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "32787:80"


  pago.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "32786:80"

