version: '3.4'

services:
  sql.data:
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "32785:1433"  

  convenio.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "32787:80"

  pago.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "32786:80"

  ocelotapigw:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "32789:80"

