// <auto-generated />
using Convenio.API.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Convenio.API.Migrations
{
    [DbContext(typeof(ConvenioContext))]
    [Migration("20181113043441_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Convenio.API.Convenio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Accion");

                    b.Property<string>("BaseUrl");

                    b.Property<string>("CasoUso");

                    b.Property<string>("Codigo");

                    b.Property<bool>("Estado");

                    b.Property<string>("Metodo");

                    b.Property<string>("Nombre");

                    b.HasKey("Id");

                    b.ToTable("Convenios");
                });
#pragma warning restore 612, 618
        }
    }
}
